<div id="top"></div>
<div class="header-container">
    <div class="header-main-container">
    	<div class="header">
            <div class="header-left header-menu">
				<?php echo $this->getChildHtml('header_menu') ?>
            </div>
            <div class="header-center header-logo">
				<?php if ($this->getIsHomePage()):?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><h1><strong><?php echo Mage::getStoreConfig('general/store_information/name') ?></strong></h1><img src="<?php echo Mage::registry('themeMediaUrl').Mage::getStoreConfig('milanoconfig/generaloptions/logo'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php else:?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><h2><strong><?php echo Mage::getStoreConfig('general/store_information/name') ?></strong></h2><img src="<?php echo Mage::registry('themeMediaUrl').Mage::getStoreConfig('milanoconfig/generaloptions/logo'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php endif?>
            </div>
            <div class="header-right">
				<?php echo $this->getChildHtml('top_cart') ?>
                <?php echo $this->getChildHtml('top_compare') ?>
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('topSearch') ?>   
            </div>      
        </div>
    </div>
    <?php echo $this->getChildHtml('topMenu'); ?>
    <div class="header-promo-container">
    	<div class="header">
			<?php echo $this->getChildHtml('header_promo') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('topBread'); ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
</div>